#!/bin/bash
#
# tomcat
#
# chkconfig:  2345 77 10
# description: Start up the Tomcat servlet engine.

# Source function library.
. /etc/init.d/functions

RETVAL=$
## Provide the catalina home as per your installation.
CATALINA_HOME="/apps/zeomega/apache-tomcat-7.0.42"
SERVICEOWNER="zope"

case "$1" in

 start)
        if [ -f $CATALINA_HOME/bin/startup.sh ];
          then
          echo $"Starting Tomcat"
          /bin/su $SERVICEOWNER $CATALINA_HOME/bin/startup.sh
        fi
        ;;

 stop)
        if [ -f $CATALINA_HOME/bin/shutdown.sh ];
          then
          echo $"Stopping Tomcat"
          /bin/su $SERVICEOWNER $CATALINA_HOME/bin/shutdown.sh
        fi
        ;;

 restart)
        if [ -f $CATALINA_HOME/bin/startup.sh ];
          then
          echo $"Stopping Tomcat"
          /bin/su $SERVICEOWNER $CATALINA_HOME/bin/shutdown.sh
        fi
        
        if [ -f $CATALINA_HOME/bin/shutdown.sh ];
          then
          echo $"Stopping Tomcat"
          /bin/su $SERVICEOWNER $CATALINA_HOME/bin/shutdown.sh
        fi
        ;;

 *)
     echo $"Usage: $0 {start|stop|restart}"
    exit 1
    ;;

esac

exit $RETVAL
